# Generated by Django 6.0.2 on 2026-03-03 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisContext",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_ac", models.IntegerField(default=15)),
                ("target_save_bonus", models.IntegerField(default=0)),
                ("spell_save_dc", models.IntegerField(default=15)),
                ("caster_attack_bonus", models.IntegerField(default=5)),
                ("number_of_targets", models.IntegerField(default=1)),
                ("advantage", models.BooleanField(default=False)),
                ("disadvantage", models.BooleanField(default=False)),
                ("spell_slot_level", models.IntegerField(default=1)),
                ("crit_enabled", models.BooleanField(default=True)),
                ("half_damage_on_save", models.BooleanField(default=True)),
                ("evasion_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Analysis Context",
                "verbose_name_plural": "Analysis Contexts",
                "db_table": "analysis_contexts",
            },
        ),
        migrations.CreateModel(
            name="SpellComparison",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("results", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Spell Comparison",
                "verbose_name_plural": "Spell Comparisons",
                "db_table": "spell_comparisons",
                "ordering": ["-created_at"],
            },
        ),
    ]
