# Generated by Django 6.0.2 on 2026-03-03 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("spells", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysiscontext",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_contexts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="spellcomparison",
            name="context",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comparisons", to="analysis.analysiscontext"
            ),
        ),
        migrations.AddField(
            model_name="spellcomparison",
            name="spell_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comparisons_as_a", to="spells.spell"
            ),
        ),
        migrations.AddField(
            model_name="spellcomparison",
            name="spell_b",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comparisons_as_b", to="spells.spell"
            ),
        ),
    ]
