# Generated by Django 6.0.3 on 2026-03-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_analysiscontext_save_penalty_die"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysiscontext",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Analysis Context",
                "verbose_name_plural": "Analysis Contexts",
            },
        ),
    ]
