# Generated by Django 6.0.3 on 2026-03-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_add_ordering_to_analysis_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysiscontext",
            name="spellcasting_ability_modifier",
            field=models.IntegerField(
                default=3,
                help_text="Caster spellcasting ability modifier, added to damage components with uses_spellcasting_modifier=True.",
            ),
        ),
    ]
