# Generated by Django 6.0.2 on 2026-03-03 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DamageComponent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("dice_count", models.IntegerField()),
                ("die_size", models.IntegerField()),
                ("flat_modifier", models.IntegerField(default=0)),
                ("damage_type", models.CharField(max_length=50)),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("on_hit", "On Hit"),
                            ("on_fail", "On Failed Save"),
                            ("on_success", "On Successful Save"),
                            ("end_of_turn", "End of Turn"),
                            ("per_round", "Per Round"),
                            ("delayed", "Delayed"),
                        ],
                        default="on_hit",
                        max_length=20,
                    ),
                ),
                ("on_crit_extra", models.BooleanField(default=True)),
                ("scales_with_slot", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Damage Component",
                "verbose_name_plural": "Damage Components",
                "db_table": "damage_components",
                "ordering": ["timing", "damage_type"],
            },
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("level", models.IntegerField(db_index=True)),
                (
                    "school",
                    models.CharField(
                        choices=[
                            ("abjuration", "Abjuration"),
                            ("conjuration", "Conjuration"),
                            ("divination", "Divination"),
                            ("enchantment", "Enchantment"),
                            ("evocation", "Evocation"),
                            ("illusion", "Illusion"),
                            ("necromancy", "Necromancy"),
                            ("transmutation", "Transmutation"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("casting_time", models.CharField(blank=True, max_length=255)),
                ("range", models.CharField(blank=True, max_length=255)),
                ("duration", models.CharField(blank=True, max_length=255)),
                ("concentration", models.BooleanField(default=False)),
                ("ritual", models.BooleanField(default=False)),
                ("is_attack_roll", models.BooleanField(default=False)),
                ("is_saving_throw", models.BooleanField(default=False)),
                (
                    "save_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STR", "Strength"),
                            ("DEX", "Dexterity"),
                            ("CON", "Constitution"),
                            ("INT", "Intelligence"),
                            ("WIS", "Wisdom"),
                            ("CHA", "Charisma"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("half_damage_on_save", models.BooleanField(default=False)),
                ("number_of_attacks", models.IntegerField(default=1)),
                ("crit_enabled", models.BooleanField(default=True)),
                ("aoe_radius", models.FloatField(blank=True, null=True)),
                ("damage_type", models.CharField(blank=True, max_length=50)),
                ("upcast_base_level", models.IntegerField(blank=True, null=True)),
                ("upcast_dice_increment", models.IntegerField(blank=True, null=True)),
                ("upcast_die_size", models.IntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("is_custom", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("higher_level", models.TextField(blank=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Spell",
                "verbose_name_plural": "Spells",
                "db_table": "spells",
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="SpellParsingMetadata",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("parsing_confidence", models.FloatField(default=0.0)),
                ("requires_review", models.BooleanField(default=False)),
                ("parsing_notes", models.JSONField(blank=True, default=dict)),
                ("auto_extracted_components", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Spell Parsing Metadata",
                "verbose_name_plural": "Spell Parsing Metadata",
                "db_table": "spell_parsing_metadata",
            },
        ),
    ]
