# Generated by Django 6.0.2 on 2026-03-03 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spells", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spells",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="damagecomponent",
            name="spell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="damage_components", to="spells.spell"
            ),
        ),
        migrations.AddField(
            model_name="spellparsingmetadata",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_spells",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="spellparsingmetadata",
            name="spell",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="parsing_metadata", to="spells.spell"
            ),
        ),
        migrations.AddIndex(
            model_name="spell",
            index=models.Index(fields=["level", "school"], name="spells_level_642c69_idx"),
        ),
        migrations.AddIndex(
            model_name="spell",
            index=models.Index(fields=["created_by", "level"], name="spells_created_edd246_idx"),
        ),
    ]
