# Generated by Django 6.0.3 on 2026-03-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="classes",
            field=models.JSONField(
                blank=True, default=list, help_text="List of class names that can learn this spell."
            ),
        ),
        migrations.AddField(
            model_name="spell",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, help_text="Gameplay category tags for filtering and analysis."
            ),
        ),
    ]
