# Generated by Django 6.0.3 on 2026-03-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0004_spell_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="upcast_attacks_increment",
            field=models.IntegerField(
                blank=True,
                help_text="Additional attack rolls per slot level above upcast_base_level (e.g. Scorching Ray +1 ray/slot).",
                null=True,
            ),
        ),
    ]
