# Generated by Django 6.0.3 on 2026-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0006_spell_is_auto_hit"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="half_damage_on_miss",
            field=models.BooleanField(
                default=False, help_text="Spell deals half damage on a missed attack roll (e.g. Acid Arrow)."
            ),
        ),
    ]
