# Generated by Django 6.0.3 on 2026-03-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0011_fix_summon_greater_demon_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagecomponent",
            name="uses_spellcasting_modifier",
            field=models.BooleanField(
                default=False,
                help_text="When True, the caster's spellcasting ability modifier is added to this component's damage (e.g. Cure Wounds 1d8 + mod).",
            ),
        ),
    ]
