# Generated by Django 6.0.2 on 2026-03-03 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreparedSpell",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("prepared", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prepared Spell",
                "verbose_name_plural": "Prepared Spells",
                "db_table": "prepared_spells",
                "ordering": ["spell__level", "spell__name"],
            },
        ),
        migrations.CreateModel(
            name="Spellbook",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Spellbook",
                "verbose_name_plural": "Spellbooks",
                "db_table": "spellbooks",
                "ordering": ["-updated_at"],
            },
        ),
    ]
