# Generated by Django 6.0.2 on 2026-03-03 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spellbooks", "0001_initial"),
        ("spells", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preparedspell",
            name="spell",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="prepared_in", to="spells.spell"
            ),
        ),
    ]
