# Generated by Django 6.0.2 on 2026-03-03 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spellbooks", "0002_initial"),
        ("spells", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="spellbook",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="spellbooks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="spellbook",
            name="spells",
            field=models.ManyToManyField(
                related_name="spellbooks", through="spellbooks.PreparedSpell", to="spells.spell"
            ),
        ),
        migrations.AddField(
            model_name="preparedspell",
            name="spellbook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="prepared_spells", to="spellbooks.spellbook"
            ),
        ),
        migrations.AddIndex(
            model_name="spellbook",
            index=models.Index(fields=["owner", "-updated_at"], name="spellbooks_owner_i_4e5a1c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="preparedspell",
            unique_together={("spellbook", "spell")},
        ),
    ]
