# Generated by Django 6.0.3 on 2026-03-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spellbooks", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spellbook",
            name="character_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("artificer", "Artificer"),
                    ("bard", "Bard"),
                    ("cleric", "Cleric"),
                    ("druid", "Druid"),
                    ("paladin", "Paladin"),
                    ("ranger", "Ranger"),
                    ("sorcerer", "Sorcerer"),
                    ("warlock", "Warlock"),
                    ("wizard", "Wizard"),
                ],
                help_text="Primary class — used to filter the Add Spells picker by default.",
                max_length=50,
            ),
        ),
    ]
