# Generated by Django 6.0.3 on 2026-03-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spellbooks", "0007_spellbook_character_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="portrait_color",
            field=models.CharField(
                choices=[
                    ("violet", "Violet"),
                    ("crimson", "Crimson"),
                    ("emerald", "Emerald"),
                    ("sapphire", "Sapphire"),
                    ("amber", "Amber"),
                    ("teal", "Teal"),
                    ("indigo", "Indigo"),
                    ("gold", "Gold"),
                    ("ruby", "Ruby"),
                    ("forest", "Forest"),
                    ("slate", "Slate"),
                    ("rose", "Rose"),
                    ("copper", "Copper"),
                    ("midnight", "Midnight"),
                    ("ivory", "Ivory"),
                    ("obsidian", "Obsidian"),
                    ("white", "White"),
                ],
                default="violet",
                help_text="Accent color for this character's shelf.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="spellbook",
            name="book_color",
            field=models.CharField(
                choices=[
                    ("violet", "Violet"),
                    ("crimson", "Crimson"),
                    ("emerald", "Emerald"),
                    ("sapphire", "Sapphire"),
                    ("amber", "Amber"),
                    ("teal", "Teal"),
                    ("indigo", "Indigo"),
                    ("gold", "Gold"),
                    ("ruby", "Ruby"),
                    ("forest", "Forest"),
                    ("slate", "Slate"),
                    ("rose", "Rose"),
                    ("copper", "Copper"),
                    ("midnight", "Midnight"),
                    ("ivory", "Ivory"),
                    ("obsidian", "Obsidian"),
                    ("white", "White"),
                ],
                default="violet",
                help_text="Spine color displayed on the library shelf.",
                max_length=30,
            ),
        ),
    ]
