# Generated by Django 6.0.3 on 2026-03-13 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spellbooks", "0008_add_white_book_color"),
        ("spells", "0008_damagecomponent_upcast_dice_increment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spellbook",
            options={
                "ordering": ["sort_order", "-updated_at"],
                "verbose_name": "Spellbook",
                "verbose_name_plural": "Spellbooks",
            },
        ),
        migrations.AddField(
            model_name="spellbook",
            name="label_color",
            field=models.CharField(
                blank=True,
                help_text="Optional spine text color override (empty = use palette default).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="spellbook",
            name="sort_order",
            field=models.IntegerField(
                default=0,
                help_text="Display position within a character's shelf (lower = further left).",
            ),
        ),
        migrations.AddIndex(
            model_name="spellbook",
            index=models.Index(fields=["owner", "sort_order"], name="spellbooks_owner_i_a99914_idx"),
        ),
    ]
